# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

branches:
  only:
    - master

language: r

warnings_are_errors: false
cache: packages

r:
  - oldrel
  - release
  - devel
